### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by ollu** [thefrontside/emberx-range-input#19]
Hi,

I'm trying to install your component but I seem to fail and I only get this error message saying:
"Compile Error: x-range-input is not a helper". I'm quite new to ember so my guess is that I miss something in the process.

What I do is  
`$ ember install emberx-range-input`

then I call your component in my -hbs-file  
`{{x-range-input min=0 max=15 step=1 value=saturationPercentage action=(action "updateSaturation")}}`

I have also added the updateSaturation function to my controller.
```
ember-cli: 2.11.0
node: 4.2.6
os: darwin x64
```

Is there any further steps I have to take to make it work?

regards, Ola

**Comment by Robdel12** [comment]
Hm that's interesting. Could you create a throw away ember project and install x-range-input there? I was able to create a fresh 2.11 ember / ember-cli project with no issues.

**Comment by ollu** [comment]
I've created a fresh Ember project with just the application.hbs and then installed the component. You can find a github project for it here: [https://github.com/ollu/x-range-input](https://github.com/ollu/x-range-input)

Thanks for any help!

**Comment by Robdel12** [comment]
Hm, I cloned it and wasn't able to reproduce. 
![image](https://cloud.githubusercontent.com/assets/2072894/22863991/ae919862-f10e-11e6-8196-89681f5054aa.png)

**Comment by ollu** [comment]
I'm not sure what I did different this time but now it's working. Maybe I forgot to restart Ember serve though I'm pretty sure I did. 
Well what do I know ... thanks for your time!

After a few minutes of thinking I rembered that I changed Node version to v6.9.5 which might have been the case.

**Comment by Robdel12** [comment]
Good to know it's resolved! :)
