### ISSUE TITLE
Does not work in IE11

### ISSUE THREAD

**Issue by optikalefx** [thefrontside/emberx-range-input#8]
Tested on browser stack, the action never gets called and my own observers on the value binding don't fire either.

**Comment by optikalefx** [comment]
See details here https://github.com/emberjs/ember.js/issues/13255

**Comment by optikalefx** [comment]
See https://github.com/thefrontside/emberx-range-input/pull/9 for temp fix

**Comment by Robdel12** [comment]
I'm going to dump some quick research I've done here. 

Only IE 9-11 treats `onchange` like `oninput` and MS Edge treats `oninput` like it should. Here's a really good breakdown of all the browsers and how they handle `oninput` vs `onchange`: 
http://www.impressivewebs.com/onchange-vs-oninput-for-range-sliders/

It doesn't look like we can feature detect for oninput: https://github.com/Modernizr/Modernizr/issues/210

So it looks like we might end up having to browser sniff, as much as it hurts to say 😢

**Comment by Robdel12** [comment]
Should be fixed with #12
